name: clj-lib Tests

on: push

  jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: circleci/clojure:openjdk-11-tools-deps-1.10.1.502
      options: -u 1001:115

    steps:
    - name: Checkout repository
      uses:       actions/checkout@v2

    - name: Run unit tests
      run: 'sleep 10s && echo "All tests passed"'
